# Site settings
title: turu.in
email: iturunen@sonatype.com
description: > # this means to ignore newlines until "baseurl:"
  Technologically oriented thoughts of Ilkka Turunen cast in to the aether. Thoughts are my own and may not reflect my employer's views.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://turu.in" # the base hostname & protocol for your site
twitter_username: ilkkaturunen
github_username:  ile2


permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 3

# Build settings
markdown: kramdown
highlighter: pygments
